id: opecha:P005382
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC414
  title: སྦྱོར་བ་བརྒྱ་པའི་དཀའ་མཆན། གསོ་དཔྱད་ཉེར་མཁོ་གཅེས་བསྡུས། ཟིན་ཏིག་ནོར་བུ་ཀེ་ཏ་ཀའི་དོ་ཤལ།
  volume: ''
  author: ''
