id: P005382
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC414
  title: སྦྱོར་བ་བརྒྱ་པའི་དཀའ་མཆན། གསོ་དཔྱད་ཉེར་མཁོ་གཅེས་བསྡུས། ཟིན་ཏིག་ནོར་བུ་ཀེ་ཏ་ཀའི་དོ་ཤལ།
  author: ''
  volumes:
    146758fd422a4bb190d4cbe73b910362:
      image_group_id: I2PD18364
      title: ''
      volume_number: 1
      total_pages: 298
      base_file: v001.txt
